name: "Update repo With SSH"
description: "Update repo With SSH"

inputs:
  shell: 
    description: "Define the shell to run command. Default: bash"
    default: 'bash'
  branch: 
    description: "Define the branch to update. Default: main"
    default: 'main'
  commit: 
    description: "Define the message to commit."
    default: "github actions auto updated at $(date '+%Y-%m-%d %H:%M:%S')"

runs:
  using: "composite"
  steps:
  - name: Update a repo With SSH
    shell: ${{ inputs.shell }}
    run: |
      git pull
      git add .
      git commit --allow-empty -m "${{ inputs.commit }}"
      git push origin ${{ inputs.branch }}

